import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';

// Helper function to get the initialized document
export async function getGoogleSheet(sheetId: string) {
  // Initialize auth
  const serviceAccountAuth = new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
    key: process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g, '\n'), // Handle newlines in the private key
    scopes: [
      'https://www.googleapis.com/auth/spreadsheets',
    ],
  });

  const doc = new GoogleSpreadsheet(sheetId, serviceAccountAuth);

  try {
    await doc.loadInfo(); // loads document properties and worksheets
    return doc;
  } catch (error) {
    console.error("Error connecting to Google Sheets:", error);
    throw error;
  }
}
